document: feedback-pipeline-workload
version: 1
data:
  name: liveinstall packages
  description: LiveInstall packages not in RHEL
  maintainer: tdawson
  packages: []
  arch_packages:
    aarch64:
      - anaconda-live
      - livesys-scripts
      - slitherer
    x86_64:
      - anaconda-live
      - livesys-scripts
      - slitherer
  labels:
    - eln-extras
